--- 
jobs: 
  build: ~
 # runs-on: ubuntu-latest
  steps: 
      #- uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with: 
          distribution: adopt
          java-version: "11"
      - name: "Build with Maven"
        run: "mvn -B package --file pom.xml"
