
env:
  STACK: java
  BUILD_TECH: java_maven
  MVN_ARGS: --batch-mode --update-snapshots verify
  CONTINUE_ON_ERROR: false
  CONTINUE_ON_ERROR_SETUP: true
  JOB_STATUS_CODE: 0

#on: [push]
# Define on which event the pipeline will be triggered
on:
  push:
  # and the target with some regex to match specific  branch names
    branches:
      - master
      - 'FEATURE-[0-9]-[0-9]-[0-9]-X-BRANCH'
      - '[0-9]_[0-9]_x'
      - '[0-9]-[0-9]-X-BRANCH'
  pull_request:
    branches:
      - master
      - 'FEATURE-[0-9]-[0-9]-[0-9]-X-BRANCH'
      - '[0-9]_[0-9]_x'
      - '[0-9]-[0-9]-X-BRANCH'

jobs:
#  pre-commit:
#    runs-on: ubuntu-latest 
#      
#    steps:
#      - name: Set up pre-commit cache
#        id: commit_check
#        uses: pre-commit/action@v2.0.0
#        with:
#          extra_args: --files ${{steps.file_changes.outputs.files}}
#
#      - name: PR comment
#        if: failure()
#        uses: actions/github-script@v4
#
#        with:
#          github-token: ${{secrets.GIT_TOKEN}}
#          script: |
#
#            github.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: ' Ups, something went wrong. Please checkout the following error:  '
#            });
  Build:
    runs-on: ubuntu-latest 
    
    steps:
    ######## Checkout code ########
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
          
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Deployment Started
          notification-color: 17a2b8
#      - name: show job status
#        if: always()
#        run: echo ${{ job.status }}
#      - name: fail the job
#        run: exit 1
        
#      - name: set_step_status
#        if: ${{ job.status == 0 }}
#        run: |
#          echo ::set-env JOB_STATUS_CODE=2
      ######## Setup JDK 11 ########
      - name: Set up JDK 11
        id: setup_jdk
        if: ${{ env.STACK == 'java' }}
        uses: actions/setup-java@v2
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
        with:
          java-version: '11'
          distribution: 'adopt'
          
#      - name: Print Setup status
#        run: echo ${{ steps.setup_jdk.outcome }}
        
      ######## Build - Maven ########
      - name: Build with Maven
        if: ${{ env.BUILD_TECH == 'java_maven' }}
        run: mvn ${{ env.MVN_ARGS }}
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
    
      ######## Build - Ant ########
      - name: Build with Ant
        if: ${{ env.BUILD_TECH == 'java_ant' }}
        run: ant -noinput -buildfile build.xml
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
    
    
      ######## Build - Gradle ########
      - name: Validate Gradle wrapper
        if: ${{ env.BUILD_TECH == 'java_gradle' }}
        uses: gradle/wrapper-validation-action@v1
        continue-on-error: ${{ env.CONTINUE_ON_ERROR_SETUP }}

      - name: Build with Gradle
        if: ${{ env.BUILD_TECH == 'java_gradle' }}
        run: ./gradlew build
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}


      ######## JUnit Test with Maven ########
      - name: Test with Maven
        run: mvn -B test --file pom.xml
        
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: tests/**/*.xml
        
      ######## Setuo .Net  ########
      - name: Setup .NET 3.x
        if: ${{ env.STACK == 'dotnet' }}
        uses: actions/setup-dotnet@v1
        continue-on-error: ${{ env.CONTINUE_ON_ERROR_SETUP }}
        with:
          dotnet-version: '3.x'

      ######## Sonar Cloud Scan ########
  Code-Quality-Check:
    needs: Build
  
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
 #       if: ${{ job.status == 2 }}
      - name: SonarCloud Scan
        run: mvn -B sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=pintu-gupta-github -Dsonar.projectKey=pintu-gupta-github
        #uses: sonarsource/sonarcloud-github-action@master
        #with:
        #  args: >
        #    -Dsonar.language=java
        #    -Dsonar.host.url=https://sonarcloud.io
        #    -Dsonar.organization=pintu-gupta
        #    -Dsonar.projectKey=pintu-gupta-github
        #    -Dsonar.projectName=simple-java-maven-app
        #    -Dsonar.projectVersion=1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  Deploy-Dev:
    environment: 'Development'
    runs-on: ubuntu-latest
    needs: Code-Quality-Check
    steps:
    - name: Deploy dev
      run: echo ${{ job.status }}
      
  Functional-Test-Regression:
    runs-on: ubuntu-latest
    needs: Deploy-Dev
    steps:
    - name: Regression
      run: echo ${{ job.status }}
      
  Functional-Test-Progression:
    runs-on: ubuntu-latest
    needs: Deploy-Dev
    steps:
    - name: Progression
      run: echo ${{ job.status }}
      
  Performance-Test:
    runs-on: ubuntu-latest
    needs: Deploy-Dev
    steps:
    - name: Peerformance-Test
      run: echo ${{ job.status }}
    
  Stage-Artifacts:
    runs-on: ubuntu-latest
    needs: Deploy-Dev
    steps:
    - name: Upload Artifacts to Artifactory
      run: echo ${{ job.status }}
