
name: CI Pipeline

on:
  push:
    branches:
      - migrate

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: |
          mvn clean
          mvn package
          java -jar target/my-app-2.0-SNAPSHOT.jar
          
      - name: Post build step 
        run: jar tf target/my-app-2.0-SNAPSHOT.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/*.xml
          
      - name: Prepare artifacts
        run: |
          mkdir -p build-artifacts
          cp target/surefire-reports/*.xml build-artifacts/
          
      - name: List files in build-artifacts
        run: ls -l build-artifacts/


  deliver:
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run deliver script
        run: ./jenkins/scripts/deliver.sh
