name: cd

on:
  pull_request:
    types:
      - closed
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          EC2_INSTANCE_IP: ${{secrets.EC2_INSTANCE_IP}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $EC2_INSTANCE_IP >> ~/.ssh/known_hosts
      - name: Connect to EC2 instance and deploy
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          EC2_INSTANCE_IP: ${{secrets.EC2_INSTANCE_IP}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_INSTANCE_IP sudo docker login -u tamarshnirer -p $DOCKER_PASSWORD 
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_INSTANCE_IP sudo docker pull tamarshnirer/helloworld
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_INSTANCE_IP sudo docker stop $(sudo docker ps -aq) || true
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_INSTANCE_IP sudo docker rm $(sudo docker ps -aq) || true
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_INSTANCE_IP sudo docker run --name helloworld -d -p 5000:5000 tamarshnirer/helloworld
