name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven 3.9.2
      run: |
        MAVEN_VERSION=3.9.2
        wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
        tar xzvf apache-maven-$MAVEN_VERSION-bin.tar.gz
        sudo mv apache-maven-$MAVEN_VERSION /opt/maven
        sudo ln -sf /opt/maven/bin/mvn /usr/bin/mvn
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

    - name: Verify Maven version
      run: mvn -version

    - name: Update Maven version
      id: update_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        PATCH=$(echo $VERSION | cut -d'.' -f3)
        NEW_PATCH=$((PATCH+1))
        NEW_VERSION=$(echo $VERSION | sed "s/$PATCH\$/$NEW_PATCH/")
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
        echo "NEW_VERSION: $NEW_VERSION" # Debugging line to check the value of NEW_VERSION
        # Update the version in pom.xml
        mvn versions:set -DnewVersion=$NEW_VERSION

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app-${{ env.new_version }}
        path: target/*.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.new_version }}

    - name: Commit and push new version
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add pom.xml
        git commit -m "Update version to ${{ env.new_version }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy Docker Image
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i "~/.ssh/id_rsa" ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.new_version }}
          if [ $(docker ps -q -f name=my-app) ]; then
            echo "Stopping and removing existing container"
            docker stop my-app && docker rm my-app
          else
            echo "No existing container to stop and remove"
          fi
          docker run -d --name my-app -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.new_version }}
        EOF
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ env.new_version }}