name: Dependency Scan

on: [push]

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit
