name: CI/CD - Build and Push Docker Image, then deploy to EC2

on:
  push:
    branches:
      # Replace with your desired branch
      - master
    # Trigers only by changes in those files/directories
    # paths:
    #   - "dockerfile"

env:
  IMAGE_NAME: joska99/java-maven
  TAG_VERSION: 0.0.${{ github.run_number }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        # Add login credentials to the repository secrets
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

      - name: Build and push Docker image tag from build number
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}

      - name: Build and push Docker image tag LATEST
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY_JOSKA_EC2 }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo docker run -d joska99/java-maven:0.0.${{ github.run_number }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-push
  #   steps:
  #     - name: Deploy to EC2
  #       uses: appleboy/ssh-action@v1.0.2
  #       with:
  #         host: ${{ secrets.EC2_IP }}
  #         username: ${{ secrets.EC2_USER }}
  #         key: ${{ secrets.SSH_KEY_JOSKA_EC2 }}
  #         port: ${{ secrets.SSH_PORT }}
  #         script: |
  #           sudo apt-get update
  #           sudo apt-get install -y python3-pip
  #           sudo pip3 install ansible

  #           ansible-playbook playbook.yaml
