name: Java CI

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: git config --global user.email "${{github.actor}}@github.com"
    - run: git config --global user.name "${{github.actor}}"
    - run: git switch -c workflow-branch
    - run: git status
    - run: git branch
    - run: echo "Hello" > test-reports/hello.txt
    - run: git add test-reports/hello.txt
    - run: git commit -m "Hello"
    - run: git push
