name: GitHub Action Java CI/CD with Maven

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v3
        with:
          github-token: ${{ secrets.TOKEN_GIT }}
        env:
          VERSION: "${{steps.bump.outputs.version}}"

      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"

      - name: Build the docker image
        run: docker build -t yaelbenyair/java-maven:${{steps.bump.outputs.version}} --build-arg="VERSION=${{steps.bump.outputs.version}}" .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push to docker hub
        run: docker push yaelbenyair/java-maven:${{steps.bump.outputs.version}}

      - name: push latest
        run: |
          docker tag yaelbenyair/java-maven:${{steps.bump.outputs.version}} yaelbenyair/java-maven
          docker push yaelbenyair/java-maven

          #deploy:
    #needs: build


