name: Maven and Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Increment Maven Version
      run: |
        mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        git add pom.xml
        git commit -m "Increment Maven version [skip ci]"

    - name: Build and Push Docker Image
      run: |
        docker build -t talibro/simple-java-maven-app:latest .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push talibro/simple-java-maven-app:latest

    - name: Push to GitHub
      run: |
        git push origin main

    # Optionally, you may want to trigger another workflow or do additional steps after pushing to GitHub.
    # For example, you could trigger a deployment workflow, create a GitHub release, etc.
