name: Maven build with JaCoCo

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
      id: extract_branch

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt-openj9'

    - name: Build with Maven
      run: mvn package

    - name: Generate JaCoCo report
      run: mvn jacoco:report

    - name: Publish JaCoCo report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/index.html
        
    - name: Publish JaCoCo report
      uses: actions/download-artifact@v3
      with:
        name: jacoco-report
    - name: check
      run: |
        ls -ltr

    - name: Add coverage to PR
      uses: madrapps/jacoco-report@v1.3
      with:
          paths: ${{ github.workspace }}/target/site/jacoco//jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
