name: Java CI with Maven

on:
  push:
    branches: [ "feature" ]

jobs:
  deploy_maven_docker:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: update version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q)
        PATCH=$(echo $VERSION | cut -d '.' -f 3 | cut -d '-' -f 1)
        INCREASED_VERSION=1.0.$((PATCH + 1))
        mvn -U versions:set -DnewVersion=${INCREASED_VERSION}

    - name: Commit updated new pom.xml
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add pom.xml
        git commit -m "Update pom.xml version"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set env
      run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: sharon088/simple_maven_java:${{ env.DATE }}  


    - name: docker run
      run: |
        docker run --rm sharon088/simple_maven_java:${{ env.DATE }}
