name: Java CI with Maven
on:
  push:
    branches: [ "master", "dev" ]

jobs:
  snyk-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=critical

  Trivy-and-versioning:
    runs-on: ubuntu-24.04
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Scan Dockerfile with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
      - name: Fetch last tags and set version
        id: version
        run: |
          git fetch --tags
          VERSION=$(git tag | sort -V | tail -n 1)
          echo "My Latest version: $VERSION"
          
          VERSION_PARTS=(${VERSION//./ })
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          NEW_PATCH_NUM=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH_NUM}"
          mvn versions:set -DnewVersion=$NEW_VERSION
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=new_version::$NEW_VERSION"
          echo "Final new_version=$NEW_VERSION"
      - name: Push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_TAG=${{ env.new_version }}
          git tag $NEW_TAG
          git push origin $NEW_TAG

  Login:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  Build:
    runs-on: ubuntu-24.04
    needs:
      - Trivy-and-versioning
    steps:
      - name: Build and push to Docker-Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: matankaufman/maven-hello-world:${{ needs.Trivy-and-versioning.outputs.new_version }}



      - name: Pull and Run from Dockerhub
        run: |
         docker pull matankaufman/maven-hello-world:${{ needs.Trivy-and-versioning.outputs.new_version }}
         docker run  --name maven_hello_world matankaufman/maven-hello-world:${{ needs.Trivy-and-versioning.outputs.new_version }}


