name: TruffleHog OSS
on: [push, pull_request]
jobs:
  scanning:
    name: TruffleHog scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #  with:
      #   fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  
